keys:
  - admins:
      - &troy E47C0DCD2768DFA138FCDCD6C67C9181B3893FB0
  - hosts:
      - &workstation-home 53BA215C79CFD829A722D5DDB05F6ED222F19591
      - &server-cloud 42C8BBCD9A7DE7B57BAD1F094B256820C0436DE2
      - &server-home 17FAFE530FE224329364AF592CEEC25DA1EED534
creation_rules:
  - path_regex: machines/configuration/workstations/home/secrets.yaml
    key_groups:
      - pgp:
          - *troy
          - *workstation-home
  - path_regex: machines/configuration/servers/cloud/secrets.yaml
    key_groups:
      - pgp:
          - *troy
          - *server-cloud
  - path_regex: machines/configuration/servers/home/secrets.yaml
    key_groups:
      - pgp:
          - *troy
          - *server-home
  - path_regex: terraform/secrets.yaml
    key_groups:
      - pgp:
          - *troy
