* TODO.org

** Code cleaning
+ I have a nix flake check now, but it does not check if my packages build successfully. How can I incorporate that?
+ Host names should be completely specified by the directory containing the machine configuration.
+ Modularize my Terraform code.
+ I should keep the machine names short, i.e. to a single word: cloud-server -> cloud, virtual-devbox -> devbox.
+ Make the cloud-server storage impermanent using impermanence and remove the impermanence parameter altogether. All machines should run impermanence.

** Data science
+ Unfortunately, I have not found that poetry2nix is 100% effective. It often happens that I am missing some module or library and I don't know how to add it. My current workflow is to use a Dockerfile, which also works but is not as reproducible.
+ I would like to move over my data-science scratchpad and use poetry2nix for it. Maybe give it a try with a single example like the red-wine data?

** Desktop
+ For my use case, maybe Syncthing is not the best solution. I sometimes end up with sync-conflicts where I do not think there should be. This has me worried that Syncthing might accidentally delete files I do not want to have deleted. Maybe Unison is a better tool for me?
+ B00merang-Project's Windows themes to make it easier for any guests?
+ Use headphones to start and pause videos / music
+ Receive a notification when the battery is low (at 20% and at 10%). That should be easy with Dunst.
+ Set up a nice notification theme for increasing / decreasing brightness and volume
+ Set up rofi-pass
+ Set up a consistent Nix color scheme using nix-colors
+ Save a predefined set of i3 window layouts
+ The Nitrokey app icon should appear in the bottom bar upon startup
+ Change my cursor theme
+ betterscreenlock automatically locks after 10 mins, even when a video is playing
+ Add icons to Polybar
+ Add volume to Polybar
+ Add brightness to Polybar
+ Add music player to Polybar
+ Add Bluetooth to Polybar
+ Add networks to Polybar
+ Add VPN to Polybar
+ Add active window (i3) to Polybar
+ Add temperature to Polybar
+ Add hard disk drive remaining and tmpfs size remaining to Polybar

** Emacs
+ Move my config to the extraConfig field so I can prepare for separating out Emacs as a subdirectory of monorepo.
+ Add LaTeX configuration to Emacs again so I can start adding notes with equations.
+ Would it make sense to switch from org-roam to denote? org-roam has a lot of features, but I do not need most of them, whereas for example a file renaming feature I do miss.
+ Since I discovered docker-tramp, would it make sense to stick to Eglot? I liked it quite a lot and I do not really see a need to download language servers inside of my Docker container as lsp-docker does. I am not sure why you would even want that, or do I misunderstand the lsp-docker package?
+ With docker-tramp, it is important to find out which packages are being used for linting and testing. Do these dev packages live inside the Docker container or on my operating system?
+ It would be great if I manage to get org-transclusion to work. I would also like some sort of annotation package like org-remark or annotate. However, the annoying part is that it couples to my file location. If I change the file location, does it break all the notes?
+ It would be nice if there is a simple function I can use that temporarily makes a buffer full-frame size. Like a full-screen button such that when I press it again, it automatically gives me back my original frame layout.
+ Solaire mode seems to be messing with the message buffer. It rapidly changes colour when I am typing. Why is that happening?
+ When I am creating my emacs-init, it is best to stick as closely as possible to Lisp configuration. This makes it very easy for me to interactively check code from the Nix file that describes my init file.
+ The terminal version of Emacs has difficult to read colours for magit. I should fix that.
+ Sometimes I need to pull in multiple elisp files of the same repository with use-package. Is this how it is supposed to be done?
+ Set up org-babel for Python so I can start moving over my data-science scratchpad.
+ The message buffer has a different colour in solaire-mode. Can I fix this somehow?
+ It might be good to have multiple font sets I can use with fontaine. Sometimes this font is a bit big. What would be nice and why?
+ We need to extract the monorepo directory as a parameter to parameters.nix. Then we can set the org directory in org/default.nix and carry it through with _modules.args to org-roam, where we use it to set the notes and templates directories as parameters, keeping everything modular. The problem currently is that we cannot set them as an environment variable when using emacsclient, since it seems emacsclient starts before the variables are set.
+ My mode-line seems to be too wide. I don't know why that happened in the first place.

** Hardware
+ Add my Raspberry Pi to my network.
+ Use Disko instead of scripted partitioning.
+ Start using LUKS Disk Encryption
+ Create my own ISO image. When I run `nix build .#nixosConfigurations.laptop.config.system.build.isoImage`, I run into a `does not provide attribute`-error. Why is that? Shouldn't this work?

** License
+ Add license if I continue developing, but I am not sure which one is legally allowed... If there is any Emacs code in there, it should be GPL?

** Virtual machine
+ Fix the compositor issue I have on virtual-devbox. For some reason if picom is turned on, the screen only updates when the compositor has to update, such as when I full-screen a window. Why?
+ How can I ssh into a NixOS VM while setting it up? Should not be so difficult since sshd is enabled by default.
+ Modularize the hardware from my VM features. Sometimes I want to the same features on a different hardware (aarch64-linux vs. x86_64-linux). I will need to be able to plug in the right hardware easily. Check how mitchellh does this.

** Website
+ Blogs and articles should be different
  - Blogs are more opinion-based and "life lessons"
  - Articles contain more clear-cut information and can often span series
+ Would it make sense to have a cache of websites that people can request when needed?
