:PROPERTIES:
:ID:       e624dec4-80fe-41c8-bc7b-225f0199c387
:mtime:    20220406211700
:ctime:    20220322105321
:END:
#+title: Renormalization
#+filetags: :unclean:

[[id:072e66af-2413-44ef-a83a-e8ab3036cd8d][@Renormalization]]

If we have a model of a system at a microscopic level, we may apply a [[id:a8dbdb72-5100-4e10-9bda-1343cb3ac50e][Coarse-graining]] method to
describe the model at a more macroscopic level. Renormalization is a general term for any set of
techniques used to connect the description of the model on the fine-grained level to the description
on the more coarse-grained level, by essentially throwing out information that is irrelevant.

In some cases, we know what problem we want to solve and invent an algorithm, for example when
working with [[id:6315b5b4-fba3-41c1-9d98-3cab2075d4b7][JPEG compression]]. Other times, we do not know what the coarse-graining should be when
we begin, such as when considering [[id:7257acc7-52b0-495b-a77c-c0f0a5d1a15c][Clustering as a form of coarse-graining]].

Although we are coarse-graining our models, renormalization does not always simplify the models.

# TODO: How does the method in physics work exactly?
How to: [[id:e8d1957d-5812-4310-a4d2-7431604189ef][Applying the envelope method to differential equations]]

Some behaviour that signals possible divergences in a standard perturbative approach, can now
conspire to form non-trivial modification of behaviour of the global solution as a function of the
approximation parameter \( \epsilon \).

For example, we can calibrate our method when [[id:6066af96-b69a-49f8-bf9b-69186f1c7ccb][?Renormalizing the damped harmonic oscillator]]

For a very simple showcasing of the technique: [[id:9eec1b8d-b4ed-4d77-a87d-afd9a84ae3bb][?Renormalizing the exponential]]

[[id:9c43d191-cce0-414a-9ee8-f166f9ad5b0e][Using renormalization to derive the CLT]]

https://arxiv.org/pdf/hep-th/9505166.pdf
