:PROPERTIES:
:ID:       a1085e61-0103-411a-8ac4-f5319da6b3c8
:mtime:    20220409120210
:ctime:    20220218233605
:END:
#+title: Partition function
#+filetags: :unclean:

The partition function is a normalization constant that appears naturally when ensuring the
probabilities in the [[id:1e8f5ce6-7cf1-4957-bbdb-a01a67cf621d][Boltzmann distribution]] sum to one. This means the partition function has a
functional dependence on the [[id:f3e6cddf-4d91-416b-a4e7-a12d24a05ff8][Lagrange multiplier]] \( \beta \) which appears in the definition of the
distribution and is therefore often denoted as \( Z(\beta) \).

Because the partition function is defined as a sum or integral over each state, exponentially
weighted by the energy of that state, it can be interpreted as the [[id:e74cd422-0192-4377-9a1c-d957660764f0][Laplace transformation]] of the
[[id:18068fcd-a67c-434b-a303-8e70b2fbfbb6][Density of states]]. This in particular shows why the partition function plays a role similar to the
[[id:da99be38-e43b-44ba-8eaf-9fe61ad05105][Moment generating function]]. In fact, the [[id:527546b6-738d-43a0-aa0c-5afdbfa250bc][?Moment generating function of the Bolztmann distribution]]
is proportional to a shifted partition function.

# TODO: Which entropy are we talking about exactly? The Gibbs entropy?
Because the partition function is a proportionality constant with dependence on [[id:f3e6cddf-4d91-416b-a4e7-a12d24a05ff8][Lagrange
multipliers]], it is often more natural to consider its logarithm. This function is known as the
[[id:a77d96b0-2010-45b9-abba-1adc27f037ee][Helmholtz free entropy]] and can be interpreted as the [[id:1d37c4ed-73f1-42e6-9b69-86cd8a1aca20][Legendre transformation]] of the [[id:6aa59df5-de7c-4fa9-8384-06ebe0cf771f][Entropy]].

The [[id:8fc593a2-cc19-4bff-a94b-37c3d37282d6][Hessian]] of the logarithm of the partition function gives rise to the [[id:f16ab982-752c-40c2-bf0d-8f674f00ba58][Covariance matrix]], which
is known to be positive semi-definite. This is key in making the connection to [[id:af2992e5-49f4-486e-aafe-2c7d5b7f9acb][Information geometry]]
apparent, because in the special case of the [[id:1e8f5ce6-7cf1-4957-bbdb-a01a67cf621d][Boltzmann distribution]] this is precisely the [[id:83601649-3af6-42c0-b54b-032150ce4787][Fisher
information metric]]. This endows the space of [[id:f3e6cddf-4d91-416b-a4e7-a12d24a05ff8][Lagrange multipliers]] with a [[id:474eb746-d6ff-4e70-a8fd-eadc2eeca52d][Riemannian metric]].
