:PROPERTIES:
:ID:       ac7e16a8-b0c0-430c-b936-1849e67ccaba
:mtime:    20221109152235
:ctime:    20221109151355
:END:
#+title: Trunk-based development
#+filetags: :stub:

Instead of having multiple long-lived feature branches that get merged with a development branch, trunk-based development encourages short-lived branches and merges directly into a main branch.

[[id:c7c31f73-abef-4437-824b-f1f1f5c8793e][Feature branches]] can still be long-lived, but they at the very least need to merge or rebase the main branch on a daily basis.

The idea of trunk-based development falls under [[id:a864d414-5a34-4562-95b8-ea3330da9e42][Continuous delivery]].

The advantage of trunk-based development is that it saves developers from large [[id:f5e6eeae-100a-4dee-af5a-aa236bbfe2f5][Merge conflicts]]. Instead, the main branch is the [[id:258a0c61-3eb2-47a2-ad2d-29eaba4be502][Single source of truth]] for the code base.

However, implementing trunk-based development requires setting up tools that enable effective development in this way. For example, two [[id:c7c31f73-abef-4437-824b-f1f1f5c8793e][Feature branches]] pushing to the same development environment can cause interference between developers. At least, an environment should be claimed temporarily until the feature branch has been rounded off and can be merged into the main branch.
