:PROPERTIES:
:ID:       48ab37e1-7c54-4e53-9e02-e898d2fb5766
:ROAM_ALIASES: BTYD
:mtime:    20220318114007
:ctime:    20220318113222
:END:
#+title: Buy Till You Die
#+filetags: :stub:

The Buy Till You Die (BTYD) models are a class of statistical models that capture the behaviour of
non-contractual customers. They can be used to determine [[id:b4e06778-26c0-4c85-96d4-bca9c4c2f785][Customer lifetime value]] or as a form of [[id:bca7fabd-8b89-433d-97ec-7e70e7be42be][Churn prediction]].

Customers are assumed to either be in an alive or a dead state. While they are alive, they will
make purchases according to a specific statistical model. The BTYD models therefore combine two
separate statistical processes:
- Behaviour of customers while they are alive.
- Dropout process from alive to dead.

Two well-known versions of BTYD are:
- [[id:1721d4e0-650a-4366-a163-27e68e45bdde][Pareto/NBD model]]
- [[id:899e57aa-8f20-4753-a972-4fe401b9c4b7][Beta-Geometric/NBD model]]

The BTYD models are examples of [[id:361223d4-c9ad-4595-b6e8-e071ee0eb987][Mixture models]].

# TODO: Be more specific about how they are examples of mixture models.
# TODO: Are BTYD models generative models?
Possible link: [[id:1c4460ec-e370-448e-a961-1ab6c899fa61][Generative model]].
