:PROPERTIES:
:ID:       28a98009-3d8e-4a4d-8845-0d89dde7bd93
:mtime:    20220328194012
:ctime:    20220328135830
:END:
#+title: Motivating the functional form of entropy
#+filetags: :stub:

If we consider [[id:291d6e23-bf39-4e16-99ac-a45daaf96adc][?Stirling's approximation applied to the multinomial coefficients]], we see that the
entropy appears naturally through the application of [[id:1f2a060d-f682-4cb3-8e84-43b0595f84a3][Stirling's approximation]] to the [[id:2d056106-74f8-484b-997a-3f9c270b5570][Multinomial
coefficients]].

The logarithm of the multinomial coefficients have some desirable properties that carry over after
the approximation:

1. The maximum value is attained for \( k_1 = ... = k_m \) (or as close to equal as possible).
2. The values are symmetric under an arbitrary permutation of \( (k_1, ..., k_m) \).
3. The logarithm is non-negative and only vanishes when some \( k_i = n \).
# TODO: Fourth property is the additivity of the logarithm for non-interacting systems

Consider the case where we start with a system in a specific state and it is free to evolve by
every time step increasing some \( k_i \) by 1 and decreasing some \( k_j \) by 1, possibly the
same state.

# TODO: Move this Markov chain to the second law of thermodynamics.
# TODO: Take the two gas bottle example of the Markov chain and calculate the steady state.
# TODO: Should we have a separate note type for illuminating examples that connect different fields?
This defines a [[id:00fa9c4b-ce93-43a3-b0d8-a99f2aad4625][Markov chain]] with \( n^2 \) possible state transitions and [[id:f87cfbed-01da-4bcc-b89f-6a7510e0f213][Transition probability
matrix]] given by:

\[
\mathbb{P}(k_i \rightarrow k_j)
&= \mathbb{P}_{ij} \\
&= \frac{k_i k_j}{n^2}
\]

In the long-time limit, this Markov chain reaches the [[id:7fb9079c-7485-4a0e-a1a7-dea306afa992][Steady state distribution]] defined by

\[
p(k_1, ..., k_m) = \frac{n!}{k_1! ... k_m!}
\]
