:PROPERTIES:
:ID:       df7f9b97-9596-4838-9dd4-97e51beafad7
:mtime:    20220314204102
:ctime:    20220314200130
:END:
#+title: UMAP versus t-SNE
#+filetags: :unclean:

UMAP and [[id:3d9fb638-d7c9-40e2-a97e-54a330489cea][t-SNE]] are very similar, but there are a couple of differences:
- t-SNE starts with a random initialization of the low-dimensional graph, but UMAP uses [[id:a5730b51-eabb-4d52-8a48-e886aa943b46][Spectral
  embedding]] to initialize the low-dimensional graph. Hence UMAP always starts with the same
  low-dimensional graph.
- t-SNE moves every point a little bit every iteration, but UMAP can move just a single point or a
  small subset of points every iteration, so it scales well with large datasets.

UMAP uses an exponentially decaying [[id:c40ccc4d-aa32-431e-ad04-60f120b6f858][Similarity measure]] such that the function is always one for the
similarity to the nearest neighbour and such that the sum of all similarities is \(
log_2(\mathrm{\#NN}) \).

t-SNE on the other hand uses a Gaussian function to calculate the similarity. The nearest
neighbours parameter is similar to the perplexity parameter for t-SNE.

t-SNE makes things symmetric by averaging the similarities, but for UMAP we take \( (S_1 + S_2) -
S_1 S_2 \). This is the [[id:f60c5302-be0d-4abb-abcc-dcba8bad0ac2][Fuzzy union operation]].

The low dimensional similarities follow a fixed [[id:5af400fc-a90b-4f8e-8c8a-02557ca62dbf][t-distribution]]. For UMAP we have scores:

\[
\frac{1}{1 + \alpha \mathbf{d}^{2\beta}}
\]

By default \( \alpha = 1.577 \)  and \( \beta = 0.8951 \) whereas for t-SNE we always have \(
\alpha = \beta = 1 \). So UMAP gives us more control over how tightly we want to pack the
lower-dimensional points together.
