:PROPERTIES:
:ID:       461ab64c-a11e-4f84-b7e9-214284dbe960
:mtime:    20220309105837
:ctime:    20220218231301
:END:
#+title: Hash function

A hash function is an algorithm that maps data of arbitrary size to a bit array of a fixed size. Practically speaking, it is a one-way function, meaning it is infeasible to invert it.

An important property of a hash function is that its outputs are uniformly distributed over its image. This is because the [[id:599f8b91-8b12-45e1-9a56-8adeb6248ebd][uniform distribution is a maximum entropy distribution]]. When testing a hash function, the [[id:7be37ce2-b190-4936-9d33-b2709594d258][chi-squared test]] is often used a a goodness-of-fit measure.

Besides security applications, hash functions can also be used to index data in [[id:18231c8f-7b75-42ce-bc21-950aa03f34f5][hash tables]], for [[id:0d49cc0e-f0a9-4104-a657-8af6787f2ad0][fingerprinting]], to uniquely identify files such as in [[id:dd646073-93ac-436c-bd9d-3b343ee41d8b][content-addressable storage]] or as [[id:5beef60f-a505-432d-8d7c-9e0e9e128dbb][checksums]] to check accidental data corruption.

Examples of hash functions:
- [[id:0b192edb-22e6-4bc8-aed1-e4968291516b][MD5 hash function]]
