:PROPERTIES:
:ID:       1c003e23-00c2-4969-a23f-8abe316fcc77
:mtime:    20220313164859
:ctime:    20220311131506
:ROAM_ALIASES: "ROC curve"
:END:
#+title: Receiver operator characteristic curve
#+filetags: :stub:

The ROC curve can be used both to evaluate a [[id:ad3e4599-2e42-4f62-a937-85f26386d57f][Classification]] algorithm as well as a specific classifier.

Originally used during the second World War. It was necessary to tune radio equipment to get the
right trade-off between true positives and false positives.

For a particular [[id:47d76987-8935-4cde-8933-c006a7f2bb8b][False positive rate]] what is the [[id:f976663e-6586-4230-a148-1c32fb72f4d7][True positive rate]]?

The area under the ROC curve ([[id:895e8579-22cb-47f4-bcb4-a89978b9d8f8][AUC]]) tells you about the quality of the classifier as a whole.

- Random classifier: Straight line, [[id:f976663e-6586-4230-a148-1c32fb72f4d7][TPR]] increases at the same speed as the [[id:47d76987-8935-4cde-8933-c006a7f2bb8b][FPR]].
- Good classifier: [[id:f976663e-6586-4230-a148-1c32fb72f4d7][TPR]] increases faster than the [[id:47d76987-8935-4cde-8933-c006a7f2bb8b][FPR]].
- Worse than random: [[id:47d76987-8935-4cde-8933-c006a7f2bb8b][FPR]] increases faster than the [[id:f976663e-6586-4230-a148-1c32fb72f4d7][TPR]]. But! In that case just switch the
  classified points in your [[id:a798bb8f-fda8-439e-9977-783be6b9b37e][Binary classification]] and you get a good classifier again. However,
  this should not happen. Something must have gone horribly wrong in this case.
