:PROPERTIES:
:ID:       11490629-a93f-4ddf-9734-6f71f7a7d600
:ROAM_ALIASES: "Macroscopic limit"
:mtime:    20220405234907
:ctime:    20220326114020
:END:
#+title: Thermodynamic limit
#+filetags: :stub:

We let

\[
N \rightarrow \infty, V \rightarrow \infty, \frac{N}{V} = \text{constant}
\]

This means fluctuations are negligible. It follows from the [[id:22637763-04bb-49a6-b3e4-4e700b43eddd][Central limit theorem]], because
fluctuations of the mean are of the order \( 1 / \sqrt{N} \) and are thus negligible with a
macroscopic amount of particles (of the order of the [[id:82cd4b82-3d85-489b-a696-e0171d65fe74][Avogadro number]]).

In small scale systems the macroscopic quantity of interest is a random variable, but when we go to the
thermodynamic limit, the macroscopic quantity takes a definite value. (For example, limit of
Gaussian \( \sigma \rightarrow 0 \) is a \( \delta \)-distribution.)

# TODO: Make the H-stability statement into a note
It is not always possible to take this limit. For example, systems that are not [[id:152bb0a1-d963-45bc-b4f2-fb443d82712c][H-stable]] do not
have a thermodynamic limit.


- nonzero average charge density, because for periodic boundary conditions there is no consistent
  value for the electric flux and in a box regularization matter will move towards the boundaries
- some quantum mechanical systems near absolute zero, like [[id:990fe795-9597-4114-a7d8-3c53f28efc99][Bose-Einstein condensation]],
  superconductivity and superfluidity
