:PROPERTIES:
:ID:       b7103666-aa3d-4df7-8e98-da33cec0cc45
:mtime:    20220320000937
:ctime:    20220318233342
:END:
#+title: ?Asymptotic series of the exponential integral
#+filetags: :appendix:stub:

The [[id:e9f3a04e-a4b1-4408-b76f-40f86fc858b7][Exponential integral]] can be written as

\[
E_1(z) = e^z \int\limits_0^{\infty} \frac{e^{-tz}}{t+1} \, dt
\]

for \( \mathfrak{Re}(z) \geq 0 \). Naively, we may try to expand

\[
\frac{1}{t+1} = \sum\limits_{n=0}^{\infty} (-1)^n t^n
\]

and write

\begin{equation*}
\begin{align}
E_1(z)
&= e^z \int\limits_0^{\infty} \sum\limits_{n=0}^{\infty} (-1)^n t^n e^{-tz} \, dt \\
&"=" e^z \sum\limits_{n=0}^{\infty} (-1)^n z^{-n} \int\limits_0^{\infty} u^n e^{-u} \, du \\
&= e^z \sum\limits_{n=0}^{\infty} \frac{(-1)^n n!}{z^{n}}
\end{align}
\end{equation*}

Of course this is not valid because we cannot exchange the integral and summation due to the
diverging sum when \( |t| \geq 1 \). Nonetheless, let us calculate the difference between the exact
formula and the partial sums. Let

\begin{equation*}
\begin{align}
S_m(z)
&= e^z \sum\limits_{n=0}^{m} \frac{(-1)^n n!}{z^n} \\
&= e^z \int\limits_0^{\infty} \sum\limits_{n=0}^m (-1)^n t^n e^{-tz} \, dt \\
&= e^z \int\limits_0^{\infty} e^{-tz} \frac{1-(-1)^m t^m}{t+1} \, dt
\end{align}
\end{equation*}

Because the sum is finite, we may now formally exchange the sum and integral and the formula for
the partial sums is exact.

\begin{equation*}
\begin{align}
E_1(z) - S_m(z)
&= e^z \int\limits_0^{\infty} e^{-tz} \left( \frac{1}{t+1} - \frac{1-(-1)^m t^m}{t+1} \right) \\
&= e^z \int\limits_0^{\infty} e^{-tz} (-1)^m \frac{t^m}{t+1} \\
\left| E_1(z) - S_m(z) \right|
&< e^z \int\limits_0^{\infty} t^m e^{-tz} \\
&= e^z \frac{m!}{z^m}
\end{align}
\end{equation*}

Moreover, since the remainder term \( R_m(z) = E_1(z) - S_m(z) \) alternates from positive to
negative, we know that either \( S_m(z) < E_1(z)  < S_{m+1}(z) \) or the reverse inequalities must
hold. Hence, the best approximation is where the squeezing is the tightest.
