:ctime:    20220326093116
:END:
#+title: Maintaining an increasingly complex system of notes
#+filetags: :unclean:

The more notes I write, the more ideas I need to sort and connect. The [[denote:20220323T141106][Requirements for my system
of notes]] give me more concrete goals to work towards, but ultimately many of the concepts
applied to the maintenance of complex systems are fairly general.

Although [[denote:20220323T135449][Abstraction is a powerful tool to fight increasing complexity]], you should be careful not
to fall into the trap of abstracting in anticipation of complexity. Instead, [[denote:20220326T095643][Abstraction should
emerge naturally]].

# TODO: What is specifically different for maintaining notes compared to maintaining software?
- [[denote:20220324T232936][Different fields of knowledge require different styles of note taking]].
- [[denote:20220323T181411][@Keeping my notes clean]]

# TODO: Expand on the similarities between note taking, math and software engineering.
This kind of note taking is also a way to teach yourself how to maintain an increasingly complex
system. The skills tranfer. Indeed, there are many similarities between taking notes versus writing
a mathematics paper versus maintaining a complex software system. [[denote:20220326T103547][Similarities between taking
notes, writing mathematics and maintaining software]].

# TODO: Somehow mention that it normally takes a while for the notes to become useful. Their
# usefulness accumulates over time.
