#+title:      Hash function
#+date:       [2022-02-18 Fri 23:13]
#+filetags:
#+identifier: 20220218T231301

A hash function is an algorithm that maps data of arbitrary size to a bit array of a fixed size. Practically speaking, it is a one-way function, meaning it is infeasible to invert it.

An important property of a hash function is that its outputs are uniformly distributed over its image. This is because the [[denote:20220218T231903][uniform distribution is a maximum entropy distribution]]. When testing a hash function, the [[denote:20220215T214844][chi-squared test]] is often used a a goodness-of-fit measure.

Besides security applications, hash functions can also be used to index data in [[denote:20220218T231507][hash tables]], for [[denote:20220218T231532][fingerprinting]], to uniquely identify files such as in [[denote:20220218T231036][content-addressable storage]] or as [[denote:20220218T231617][checksums]] to check accidental data corruption.

Examples of hash functions:
- [[denote:20220309T105801][MD5 hash function]]
