:ctime:    20220327193222
:END:
#+title: Equipartition theorem
#+filetags: :stub:

The equipartition theorem is a key equation in [[denote:20220210T210151][Statistical physics]], describing how energy is
distributed among the microscopic degrees of freedom of a physical system. If the system has
[[denote:20220324T213756][Hamiltonian]] \( H \) with degrees of freedom \( x_n \), the equipartition theorem states that in
[[denote:20220329T234429][Thermal equilibrium]] we must find

\begin{equation*}
\begin{align}
\left\langle x_n \frac{\partial H}{\partial x_n} \right\rangle &= k_B T \qquad &&\text{for all } n \\
\left\langle x_m \frac{\partial H}{\partial x_n} \right\rangle &= 0 \qquad &&\text{for all } m \neq n
\end{align}
\end{equation*}

An important special case arises when \( H \) is a [[denote:20220409T132307][Homogeneous polynomial]] in its parameters. In
this case, the average energy does not depend on any microscopic parameters, since

\[
\sum\limits_{n=1}^d \left\langle x_n \frac{\partial H}{\partial x_n} \right\rangle = m \langle H \rangle
\]

where \( m \) is the degree of the polynomial. Then we find

\[
\langle H \rangle = \frac{d}{m} k_B T
\]

without any reference to any microscopic parameters.

Moreover, if the Hamiltonian splits in a sum Hamiltonians none of which share
variables, i.e.

\[
H(x_1, ..., x_d) = H_1(x_1, ..., x_a) + H_2(x_{a+1}, ..., x_d)
\]

we can apply the equipartition theorem to \( H_1 \) and \( H_2 \) separately. This can often be
done because the potential and kinetic energy are additive.

On physical grounds, [[denote:20220409T125024][The equipartition theorem for quadratic
degrees of freedom]]. This particular case sometimes also goes by the name of the equipartition theorem.

[[denote:20220409T140201][The equipartition theorem is a purely classical result]].

