#+title:      Percolation theory
#+date:       [2022-03-24 Thu 12:02]
#+filetags:
#+identifier: 20220324T120211

* [[denote:20220324T120224][Percolation theory]]
** General notes
- Also related to network models of epidemics

** Percolation in rocks
Conductivity of material.

Percolation theory comes from material science and from open and closed channels for a fluid to
flow. Relation to graph theory?

Simple model of a rock to investigate water flow through the rock. Say it rains, is there a puddle
under the rock?

Bunch of holes in the rock and they might be connected to each other. So random edges between
holes. Is there a path that goes all the way from the top to the bottom? Is the rock porous?

Approximating as an infinite lattice if rock is much bigger than the channels.

This is [[denote:20220324T123955][Bond percolation]].

** Basic definitions
Consider a square lattice \( \mathbb{Z}^2 \)

[[denote:20220324T123955][Bond percolation]]
All vertices present, but open edges are present only with probability \( p \).

[[denote:20220324T124131][Site percolation]]
Vertices present with probability \( p \) and all edges between neighbours are present.

** Percolation in composite wires
Electrical conductivity. Entirely made of iron, then it will be conductive. But what if some
locations in the wire are non-conductive material, because they might make the wire stronger. Is
there still a path that only touches iron? Otherwise the wire is not conductive anymore. This is an
example of *site percolation*.

We can also have an example of *bond percolation*. Sometimes polymers are scattered around. They
are insulating, but makes the wire stronger. Can get the strength of the polymer, without it being
homogeneous. We break some edges between iron atoms, but not completely surrounded by polymers.

** Basic questions
- Does there exist an infinite open cluster?
- What are the size distributions of open clusters?

** Definitions
Let our 2D edge percolation graph have vertices on \( \mathbb{Z}^2 \) and edges between all
adjacent vertices with distance 1 (vertically + horizontally). Let each edge be open with
probability \( p \) and closed with probability \( 1 - p \).

Def. Let \( C(x) \) denote the connected component \( x \) is in. \( C(x) \) is a random variable
dependent on the open edges.

Def. Let \( C = C(0) \)

Def. \( \theta(p) = \mathbb{P}_p(|C| = \infty) \)

Def. Let \( p_c \) be a constant, such that for \( p < p_c \), \( \theta(p) = 0 \) and for \( p >
p_c \), \( \theta(p) > 0 \). This is the probability of transition.

** Phase transition
Question: Is there a \( p < 1 \) such that \( \theta(p) = 1 \)? No, because there will always be a
chance that none of the four neighbouring edges around the origin are open: Indeed, this chance is \( (1-p)^4
\), so \( \theta(p) \) is at most \( 1 - (1-p)^4 < 1 \).

But [[denote:20220324T123704][Kolmogorov's zero-one law]]: Tail events have either 0 or 1 probability. If \( \theta(p) > 0  \) then
there must exists almost surely an infinite open component. This is because we have an infinite
number of points and for each point the chance of being in an infinite component is \( \theta(p) >
0 \). Hence there must almost surely be an infinite component.

This is what makes it a [[denote:20220324T123912][Phase transition]].

** Basic bound on the critical probability
Theorem. If \( p < \frac{1}{3} \), then \( \theta(p) = 0 \)

Use something like the first moment method.

Let \( F_n = \{ \text{There exists a self-avoiding open path of length n starting at 0} \} \)

For any given self-avoiding path in \( \mathbb{Z}^2 \), probability that all edges are open is \(
p^n \).

The total number of self-avoiding paths of length \( n \) must be bounded from above by \(
4(3^{n-1}) \), because you cannot back-track after the first step.

So \( \mathbb{P}(F_n) \leq 4(3^{n-1}) p^n \rightarrow 0 \text{ as } n \rightarrow \infty \) because
\( p < \frac{1}{3} \).

If we have an infinite path, than for sure we can construct a self-avoiding open path of length n.
Hence,

\( \mathbb{P}(|C| = \infty) \leq \mathbb{P}(F_n) \rightarrow 0 \text{ as } n \rightarrow \infty \)

Hence \( p_c \geq \frac{1}{3} \).

This theorem did not depend on geometry at all. This is true for any regular graph of degree 4. (Closely related to [[denote:20220324T125518][Erdős–Rényi model]].)

** Better bound by Harris (1960)
Theorem. \( \theta(1/2) = 0 \), hence \( p_c \geq \frac{1}{2} \).

*** Use self-duality of \( \mathbb{Z}^2 \).
We can define a dual graph by translating to the right by \( (0.5, 0.5) \) and defining an edge to
be present in the dual when it does not cross an edge in the original graph.

Edge probability \( p \) in original then we have edge probability of \( 1 - p \) in the dual.

Suppose \( p < p_c \). Then \( C(0) \) is finite almost surely. Hence there exists an open cycle in
the dual graph encircling 0. But then clearly the connected component of the dual graph is finite.

Conversely, if there exists an open cycle in the dual graph around 0, then \( C(0) \) is finite.

Let \( p = \frac{1}{2} \). Let's consider probability of an open cycle in an annulus (square)
composed of 4 separate paths across rectangles.

Lemma. Let \( R \) be a rectangular \( k \times l \) portion of the original lattice and let \(
R^{\prime} \) be the corresponding \( (k+1) \times (l-1) \) portion of the dual lattice.

Then there exists either an open horizontal path in \( R \) or an open vertical path in \(
R^{\prime} \).

** Reference
https://www.youtube.com/watch?v=0d46Z9vnuJU
https://www.youtube.com/watch?v=XMEXup1oabQ

* [[denote:20220322T105321][Renormalization]]
** Reference
https://guava.physics.uiuc.edu/~nigel/courses/563/Essays_2013/PDF/brodsky.pdf
