(require 'ox-hugo)
(setq org-hugo-base-dir default-directory)
(setq org-id-locations-file (concat org-hugo-base-dir ".org-id-locations"))
(setq org-directory (file-name-as-directory (getenv "blog")))

(defun build ()
  (setq org-hugo-section "blog")
  (dolist (note (directory-files org-directory t "\.org$"))
    (find-file note)
    (org-hugo-export-wim-to-md)))
