:PROPERTIES:
:ID:       244ac6a5-3cb5-43aa-9152-a9b2add9bdf3
:mtime:    20220314212109
:ctime:    20220211100608
:ROAM_ALIASES: "Hypothesis test"
:END:
#+title: Statistical hypothesis test

A statistical hypothesis test is a way to determine a possible conclusion from two different hypotheses.

In a hypothesis test, a null hypothesis and an alternate hypothesis are proposed for the underlying probability distribution of a sample of data. If the probability of occurrence is less than the [[id:fbe6b848-42ad-4e4d-8843-49353375d34c][significance level]] given that the null hypothesis is true, the null hypothesis is rejected and the alternate hypothesis accepted.

A mistaken rejection of the null hypothesis is known as a [[id:82d454aa-5c8c-4bd9-8f28-bef2c002c411][Type I error]], whereas the mistaken acceptance of an actually false null hypothesis is known as a [[id:b8e61a93-91c9-48e9-a4dc-dd9b13623706][Type II error]].

Tests based on the significance level, are another way of expressing [[id:6eda8baf-2d53-4f90-836e-6bb298ac2c55][Confidence intervals]].

There are many well-known hypothesis tests. For a list and description of when to use them, see
[[id:6b1cf466-8b45-43ca-a646-53b41a138769][!When to apply which hypothesis test]].
