:PROPERTIES:
:ID:       ee069ad2-bcf1-4dec-bce4-295bc81e74c7
:mtime:    20220423102810
:ctime:    20220221233008
:ROAM_ALIASES: DVC
:END:
#+title: Data Version Control
#+filetags: :stub:

# TODO: Write a note about the workflow with DVC vs. the workflow with git
dvc is a tool created to bring [[id:4536cafc-57c4-455c-ad8b-adf0041796b7][Reproducibility]] to the data science and machine learning workflow.

Internally, it works by saving files as [[id:dd646073-93ac-436c-bd9d-3b343ee41d8b][content-addressable storage]]. This allows dvc to version
control large files. It is easy to get started with the commands, because [[id:26f35efa-10c6-49ae-aade-cccc6784a63a][dvc mirrors the way Git
works internally]].

Unlike [[id:37605e84-f730-4469-8b73-25f8b8710754][Git LFS]], dvc does not need a server to work and can be run locally with some commands.

However, it is not enough to version the files. We also need a [[id:1653a154-c780-4b6d-987e-dba7293b70a8][Reproducible workflow]], which dvc
allows us to do with a YAML-file. This is a big advantage compared to [[id:37605e84-f730-4469-8b73-25f8b8710754][Git LFS]].

The [[id:1653a154-c780-4b6d-987e-dba7293b70a8][Reproducible workflow]] that dvc enables, makes it a good fit for [[id:3e05d23e-40a9-451e-9934-85ed62faae69][CI/CD]]. dvc uses [[id:57f71017-4de8-40b5-bb94-0edd0ac3c0ca][Cache]] to store
all intermediate results and the [[id:0b192edb-22e6-4bc8-aed1-e4968291516b][MD5 hash function]] to check which parts of the workflow need to be
rerun. For the reproducible workflow, it should be noted that there are two options:

1. dvc pulls the output files that have been saved remotely down to your local machine
2. dvc reproduces all the steps according to the locked workflow

These results can be different! If one of the steps in the workflow is not deterministic, the
output might be different from the output saved remotely.

A big difference between dvc and standard [[id:15bb787b-4ba1-46f0-8c52-e60c95961e94][Makefiles]] is that dvc relies on the [[id:0b192edb-22e6-4bc8-aed1-e4968291516b][MD5 hash function]] to
detect changes and which files to rerun where [[id:15bb787b-4ba1-46f0-8c52-e60c95961e94][Makefiles]] look at modification times and rerun all of
the changes downstream.
