:PROPERTIES:
:ID:       cffe690c-8a58-43fc-8ce6-8ac777a3acb1
:mtime:    20220315134112
:ctime:    20220303092333
:END:
#+title: GNU Guix
#+filetags: :stub:

This is the package manager on which [[id:b2430170-98ab-4801-ad2e-84a1ed686865][Guix System]] is based. It is written in [[id:473af42b-6e22-40e9-b5eb-2fa9c78484ff][Guile Scheme]].

Guix works a lot with symlinks. If we reconfigure the system or the home environment, under the
hood Guix is just changing symlinks to different files. The user experience is to receive a
completely new configuration, but if only a couple of packages need to be downloaded and symlinked,
Guix can be much faster due to this idea.

Since [[id:4adacf4a-fe73-4431-8123-04750c4b1e34][Timestamps are meaningless for reproducible builds]], Guix does not store time stamps in the
[[id:81c1b475-e974-48b3-b7d1-0ad40e24152d][GNU store]]. For [[id:4536cafc-57c4-455c-ad8b-adf0041796b7][Reproducibility]], Guix makes use of [[id:471d72fd-d53a-4826-8717-6fe5d35aa5e2][Guix channels]].

[[id:2505bd76-1c2f-49ad-863a-8dbdf9ea9edd][Guix has transactional upgrades]].

Guix also embraces the idea of [[id:fa9e775f-96c5-47d7-b2aa-b5096e313c27][Pure functions]].
- [[id:ade46a22-368d-41c0-9d2b-48c02735f901][Package builds in Guix are pure functions]].
- [[id:c156ba96-8185-428c-a674-03a1535efdc9][An operating system is the result of a function]] (See [[id:b2430170-98ab-4801-ad2e-84a1ed686865][Guix System]])
- [[id:22f981ca-6b14-491a-9f03-f4c2c59af1a0][A home environment is the result of a function]] (See [[id:462ccc41-f570-447a-904a-f487e3b7a228][Guix Home]])

For a fact sheet of commands and others, see [[id:0a7bc2b0-bd54-45ee-bcd2-d2779bdc69b6][!Guix]].

For Guix on the user level, see [[id:462ccc41-f570-447a-904a-f487e3b7a228][Guix Home]].

# TODO: Guix can also be used as a development tool for setting up isolated development
# environments
[[id:7d63d2eb-5775-4187-b88b-863e9a03fcfc][Guix as a development tool]].

https://www.youtube.com/watch?v=chKc_YsvXKU
