:PROPERTIES:
:ID:       1177ce83-7dd0-4f02-9cb7-355654092ac1
:mtime:    20220322105935
:ctime:    20220322104107
:END:
#+title: Perturbation theory
#+filetags: :stub:

Perturbation theory consists of a general set of methods used to approximate a complicated problem
by treating it as a perturbation, i.e. small deviation, of an exactly solvable problem. This is
often done order by order in a small parameter.

In the best case scenario, the generated approximate solution smoothly approaches the exact
solution. These are the cases of [[id:94a74114-4e0b-45e5-9661-465a8399d6ce][Regular perturbation problems]]. Sometimes the perturbative solution
diverges, but we may still find a descent approximation by using [[id:bafc5759-1098-48b7-b9ff-ec458d629254][Asymptotic series]].

However, it can also happen that the behaviour is severe enough that we cannot even find such an
expansion. For example, \( \epsilon \dot{x}(t) = x(t) \) has solutions of the form \( x(t) = x(0)
\exp(t/\epsilon) \)  which become meaningless in the limit \( \epsilon \rightarrow 0 \). These are [[id:7f731f53-bd0e-4b1f-8a89-1eb868688d88][Singular perturbation problems]].

There are many techniques to deal with perturbative problems. For example:
- [[id:e624dec4-80fe-41c8-bc7b-225f0199c387][Renormalization]]
